// backend/createStaffUser.js
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./src/domain/User');
const MongoUserRepository = require('./src/infrastructure/repositories/MongoUserRepository');
const dotenv = require('dotenv');

// Load env vars
dotenv.config();

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/movieticketbooking', {
  // options like useNewUrlParser are deprecated in newer mongoose but harmless usually, 
  // keeping it simple or matching project style if possible.
  // The existing createAdminUser.js used them.
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'MongoDB connection error:'));
db.once('open', async () => {
  console.log('Connected to MongoDB');
  
  try {
    const userRepository = new MongoUserRepository();
    
    const staffEmail = 'staff@example.com';
    
    // Check if staff user already exists
    const existingStaff = await userRepository.findByEmail(staffEmail);
    if (existingStaff) {
      console.log('Staff user already exists');
      process.exit(0);
    }
    
    // Create staff user
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash('staff123', saltRounds);
    
    const staffUser = new User(
      null, // ID will be generated by database
      'Staff User',
      staffEmail,
      '0987654321',
      hashedPassword,
      new Date('1995-01-01'),
      0, // initial loyalty points
      'staff'
    );
    
    const result = await userRepository.create(staffUser);
    console.log('Staff user created successfully:', result);
    process.exit(0);
  } catch (error) {
    console.error('Error creating staff user:', error);
    process.exit(1);
  }
});
