// backend/createAdminUser.js
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./src/domain/User');
const MongoUserRepository = require('./src/infrastructure/repositories/MongoUserRepository');

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/movieticketbooking', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'MongoDB connection error:'));
db.once('open', async () => {
  console.log('Connected to MongoDB');
  
  try {
    const userRepository = new MongoUserRepository();
    
    // Check if admin user already exists
    const existingAdmin = await userRepository.findByEmail('admin@example.com');
    if (existingAdmin) {
      console.log('Admin user already exists');
      process.exit(0);
    }
    
    // Create admin user
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash('admin123', saltRounds);
    
    const adminUser = new User(
      null, // ID will be generated by database
      'Admin User',
      'admin@example.com',
      '1234567890',
      hashedPassword,
      new Date('1990-01-01'),
      0, // initial loyalty points
      'admin',
      true // isVerified
    );
    
    const result = await userRepository.create(adminUser);
    console.log('Admin user created successfully:', result);
    process.exit(0);
  } catch (error) {
    console.error('Error creating admin user:', error);
    process.exit(1);
  }
});