// backend/src/application/AuthService.js
const jwt = require('jsonwebtoken');
const { OAuth2Client } = require('google-auth-library');

class AuthService {
  constructor(userService, refreshTokenRepository) {
    this.userService = userService;
    this.refreshTokenRepository = refreshTokenRepository;
    this.accessTokenSecret = process.env.ACCESS_TOKEN_SECRET || 'access_token_secret';
    this.refreshTokenSecret = process.env.REFRESH_TOKEN_SECRET || 'refresh_token_secret';
    this.accessTokenExpiration = process.env.ACCESS_TOKEN_EXPIRATION || '15m';
    this.refreshTokenExpiration = process.env.REFRESH_TOKEN_EXPIRATION || '7d';
    
    this.googleClientId = process.env.GOOGLE_CLIENT_ID || 'your_google_client_id';
    this.googleClient = new OAuth2Client(this.googleClientId);

    // Simple in-memory lock for refresh token rotation to handle extreme concurrency
    this.rotationLocks = new Map();
  }

  async verifyGoogleToken(token) {
    try {
      const ticket = await this.googleClient.verifyIdToken({
        idToken: token,
        audience: this.googleClientId,
      });
      return ticket.getPayload();
    } catch (error) {
      console.error('Google token verification failed:', error.message);
      throw new Error('Google authentication failed');
    }
  }

  async googleLogin(payload) {
    const { sub, email, name, picture } = payload;
    
    let user = await this.userService.getUserByEmail(email);
    
    if (!user) {
      // Auto-registration
      user = await this.userService.createUser({
        name: name || email.split('@')[0],
        email: email,
        googleId: sub,
        phone: null,
        password: null, // Optional now in Model
        dateOfBirth: null,
        role: 'user'
      });
    }

    const { accessToken, refreshToken } = await this.generateTokens(user);
    
    return {
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        phone: user.phone,
        dateOfBirth: user.dateOfBirth,
        loyaltyPoints: user.loyaltyPoints,
        role: user.role,
        picture: picture // Optional extra info
      },
      accessToken,
      refreshToken
    };
  }

  async generateTokens(user) {
    const payload = {
      id: user.id,
      email: user.email,
      name: user.name
    };

    const accessToken = jwt.sign(payload, this.accessTokenSecret, {
      expiresIn: this.accessTokenExpiration
    });

    const refreshToken = jwt.sign(payload, this.refreshTokenSecret, {
      expiresIn: this.refreshTokenExpiration
    });

    // Save refresh token to database
    if (this.refreshTokenRepository) {
      const expiresAt = this._getExpiryDate(this.refreshTokenExpiration);
      await this.refreshTokenRepository.create({
        userId: user.id,
        token: refreshToken,
        expiresAt: expiresAt
      });
    }

    return { accessToken, refreshToken };
  }

  verifyAccessToken(token) {
    try {
      return jwt.verify(token, this.accessTokenSecret);
    } catch (error) {
      throw new Error('Invalid access token');
    }
  }

  verifyRefreshToken(token) {
    try {
      return jwt.verify(token, this.refreshTokenSecret);
    } catch (error) {
      if (error.name === 'TokenExpiredError') {
          throw new Error('Refresh token expired');
      }
      throw new Error('Invalid refresh token');
    }
  }

  async refreshTokens(refreshToken) {
    let decoded;
    try {
      decoded = jwt.verify(refreshToken, this.refreshTokenSecret);
    } catch (error) {
        if (this.refreshTokenRepository) {
            await this.refreshTokenRepository.deleteByToken(refreshToken);
        }
        throw new Error('Invalid refresh token');
    }

    if (!this.refreshTokenRepository) {
        throw new Error('Refresh token repository not configured');
    }

    // Reuse detection: Check if token exists in database
    const tokenInDb = await this.refreshTokenRepository.findByToken(refreshToken);
    
    if (!tokenInDb) {
      // REUSE DETECTED!
      // This token was already used or invalidated. 
      // For security, invalidate ALL tokens for this user.
      await this.refreshTokenRepository.deleteAllForUser(decoded.id);
      throw new Error('Invalid refresh token');
    }

    // GRACE PERIOD LOGIC:
    // If the token was already consumed but very recently (e.g. within 30 seconds),
    // it's likely a concurrent request. We return the SAME new tokens that were 
    // generated by the first request instead of triggering reuse detection or 
    // generating another pair.
    if (tokenInDb.consumedAt) {
      const gracePeriodMs = 30 * 1000; // 30 seconds
      const timeSinceConsumption = Date.now() - new Date(tokenInDb.consumedAt).getTime();
      
      if (timeSinceConsumption <= gracePeriodMs && tokenInDb.replacedBy) {
        // Find the user and verify they still exist
        const user = await this.userService.getUserById(decoded.id);
        if (!user) throw new Error('User not found');

        // Return the replacement token information. 
        // Note: For simplicity and since access tokens are short-lived, 
        // we could just return the replacement refreshToken. 
        // However, the client expects a pair.
        // If we want to be perfect, we'd need to store the accessToken too, 
        // but generating a new accessToken for the same user is generally fine 
        // as long as we don't rotate the REFRESH token again.
        
        const payload = { id: user.id, email: user.email, name: user.name };
        const accessToken = jwt.sign(payload, this.accessTokenSecret, { expiresIn: this.accessTokenExpiration });
        
        return { accessToken, refreshToken: tokenInDb.replacedBy };
      }

      // Consumed but outside grace period -> REUSE DETECTED
      await this.refreshTokenRepository.deleteAllForUser(decoded.id);
      throw new Error('Invalid refresh token');
    }

    // Token is valid and exists in DB -> Rotate it
    
    // CONCURRENCY LOCK: Prevent multiple concurrent requests for the same token 
    // from entering the rotation logic at the same time.
    if (this.rotationLocks.has(refreshToken)) {
      // Wait for the other request to finish and then retry (grace period will handle it)
      await this.rotationLocks.get(refreshToken);
      return this.refreshTokens(refreshToken);
    }

    let resolveLock;
    const lockPromise = new Promise(resolve => { resolveLock = resolve; });
    this.rotationLocks.set(refreshToken, lockPromise);

    try {
      const user = await this.userService.getUserById(decoded.id);
      if (!user) {
        await this.refreshTokenRepository.deleteByToken(refreshToken);
        throw new Error('User not found');
      }

      // Generate new pair
      const payload = { id: user.id, email: user.email, name: user.name };
      const newAccessToken = jwt.sign(payload, this.accessTokenSecret, { expiresIn: this.accessTokenExpiration });
      const newRefreshToken = jwt.sign(payload, this.refreshTokenSecret, { expiresIn: this.refreshTokenExpiration });

      // ATOMIC-LIKE ROTATION: Mark old token as consumed and set its replacement
      const expiresAt = this._getExpiryDate(this.refreshTokenExpiration);
      
      await this.refreshTokenRepository.create({
        userId: user.id,
        token: newRefreshToken,
        expiresAt: expiresAt
      });

      await this.refreshTokenRepository.markAsConsumed(refreshToken, newRefreshToken);

      return { accessToken: newAccessToken, refreshToken: newRefreshToken };
    } finally {
      this.rotationLocks.delete(refreshToken);
      resolveLock();
    }
  }

  async authenticateUser(email, password) {
    const user = await this.userService.authenticateUser(email, password);
    if (user) {
      const { accessToken, refreshToken } = await this.generateTokens(user);
      return {
        user: {
          id: user.id,
          name: user.name,
          email: user.email,
          phone: user.phone,
          dateOfBirth: user.dateOfBirth,
          loyaltyPoints: user.loyaltyPoints,
          role: user.role
        },
        accessToken,
        refreshToken
      };
    }
    return null;
  }

  async logout(refreshToken) {
    if (this.refreshTokenRepository) {
      await this.refreshTokenRepository.deleteByToken(refreshToken);
    }
  }

  _getExpiryDate(expirationString) {
    const match = expirationString.match(/^(\d+)([smhd])$/);
    if (!match) {
      // Default to 7 days if parsing fails
      return new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    }

    const value = parseInt(match[1]);
    const unit = match[2];
    const now = Date.now();

    switch (unit) {
      case 's': return new Date(now + value * 1000);
      case 'm': return new Date(now + value * 60 * 1000);
      case 'h': return new Date(now + value * 60 * 60 * 1000);
      case 'd': return new Date(now + value * 24 * 60 * 60 * 1000);
      default: return new Date(now + 7 * 24 * 60 * 60 * 1000);
    }
  }
}

module.exports = AuthService;
