// Booking service
const Booking = require('../domain/Booking');
const User = require('../domain/User');

class BookingService {
  constructor(bookingRepository, userRepository, showtimeRepository, movieRepository, couponService, validationService) {
    this.bookingRepository = bookingRepository;
    this.userRepository = userRepository;
    this.showtimeRepository = showtimeRepository;
    this.movieRepository = movieRepository;
    this.couponService = couponService;
    this.validationService = validationService;
  }

  async _checkAgeEligibility(userId, showtimeId) {
    if (!this.userRepository || !this.showtimeRepository || !this.movieRepository) {
       console.warn('Repositories missing for age verification in BookingService');
       return; 
    }

    const user = await this.userRepository.findById(userId);
    if (!user) throw new Error('User not found');

    const showtime = await this.showtimeRepository.findById(showtimeId);
    if (!showtime) throw new Error('Showtime not found');

    const movie = await this.movieRepository.findById(showtime.movieId);
    if (!movie) throw new Error('Movie not found');

    // Rehydrate User domain entity to use domain logic
    const userEntity = new User(
      user.id,
      user.name,
      user.email,
      user.phone,
      user.passwordHash,
      user.dateOfBirth,
      user.loyaltyPoints,
      user.role
    );

    if (!userEntity.canBookMovie(movie.rating)) {
        throw new Error(`User is not old enough to watch this movie (Rated ${movie.rating})`);
    }
  }

  async createBooking(bookingData) {
    // Check age eligibility first
    await this._checkAgeEligibility(bookingData.userId, bookingData.showtimeId);

    // Coupon validation and discount application
    let finalPrice = bookingData.totalPrice;
    let originalPrice = bookingData.totalPrice;
    let discountAmount = 0;
    let appliedCouponCode = null;

    if (bookingData.couponCode && this.couponService) {
        const showtime = await this.showtimeRepository.findById(bookingData.showtimeId);
        const validation = await this.couponService.validateCoupon(bookingData.couponCode, {
            userId: bookingData.userId,
            orderTotal: bookingData.totalPrice,
            movieId: showtime.movieId
        });

        if (validation.isValid) {
            appliedCouponCode = validation.code;
            discountAmount = validation.discountAmount;
            finalPrice = Math.max(0, originalPrice - discountAmount);
            
            // Increment usage
            await this.couponService.incrementUsage(appliedCouponCode);
        }
    }

    // Check for existing held booking to upgrade
    const existingHold = await this.bookingRepository.findPendingBookingByUser(bookingData.userId, bookingData.showtimeId);

    if (existingHold) {
      // Verify all requested seats are available (or held by this user)
      for (const seatId of bookingData.seatIds) {
        const collision = await this.bookingRepository.findCollidingBooking(bookingData.showtimeId, seatId, bookingData.userId);
        if (collision) {
          throw new Error(`Seat ${seatId} is no longer available`);
        }
      }

      const updatedBooking = new Booking(
        existingHold.id,
        bookingData.userId,
        bookingData.showtimeId,
        bookingData.seatIds,
        finalPrice,
        new Date(),
        bookingData.paymentMethod === 'cash' ? 'confirmed' : 'pending',
        bookingData.paymentMethod,
        null, // expiresAt
        originalPrice,
        discountAmount,
        appliedCouponCode
      );
      
      if (updatedBooking.status === 'confirmed') {
        updatedBooking.expiresAt = null;
        if (this.validationService) {
          updatedBooking.validationToken = this.validationService.generateValidationToken(existingHold.id);
        }
      } else {
        updatedBooking.expiresAt = new Date(Date.now() + 15 * 60 * 1000); 
      }

      return await this.bookingRepository.update(existingHold.id, updatedBooking);
    }

    // New booking (fallback)
    // Check collisions first
    for (const seatId of bookingData.seatIds) {
        const collision = await this.bookingRepository.findCollidingBooking(bookingData.showtimeId, seatId, bookingData.userId);
        if (collision) {
          throw new Error(`Seat ${seatId} is no longer available`);
        }
    }

    const booking = new Booking(
      null, // ID will be generated by database
      bookingData.userId,
      bookingData.showtimeId,
      bookingData.seatIds,
      finalPrice,
      new Date(),
      bookingData.paymentMethod === 'cash' ? 'confirmed' : 'pending',
      bookingData.paymentMethod,
      null, // expiresAt
      originalPrice,
      discountAmount,
      appliedCouponCode
    );
    
    if (booking.status === 'pending') {
       booking.expiresAt = new Date(Date.now() + 15 * 60 * 1000);
    }

    const result = await this.bookingRepository.create(booking);
    
    if (result.status === 'confirmed' && this.validationService && !result.validationToken) {
      result.validationToken = this.validationService.generateValidationToken(result.id);
      return await this.bookingRepository.update(result.id, result);
    }

    return result;
  }

  async holdSeat(userId, showtimeId, seatId) {
    // Check age eligibility first
    await this._checkAgeEligibility(userId, showtimeId);

    // 1. Check if seat is already locked by someone else
    const collision = await this.bookingRepository.findCollidingBooking(showtimeId, seatId, userId);
    if (collision) {
      throw new Error('Seat is already reserved');
    }

    // 2. Find existing active hold for this user
    let booking = await this.bookingRepository.findPendingBookingByUser(userId, showtimeId);

    const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes from now

    if (booking) {
      // Check max seats (e.g. 8)
      if (booking.seatIds.length >= 8) {
        throw new Error('Maximum seat limit reached (8)');
      }
      return await this.bookingRepository.addSeatToBooking(booking.id, seatId, expiresAt);
    } else {
      const newBooking = new Booking(
        null,
        userId,
        showtimeId,
        [seatId],
        0, 
        new Date(),
        'held',
        'momo',
        expiresAt
      );
      return await this.bookingRepository.create(newBooking);
    }
  }

  async releaseSeat(userId, showtimeId, seatId) {
    const booking = await this.bookingRepository.findPendingBookingByUser(userId, showtimeId);
    if (!booking) return null;

    const updatedBooking = await this.bookingRepository.removeSeatFromBooking(booking.id, seatId);
    
    if (updatedBooking && updatedBooking.seatIds.length === 0) {
      await this.bookingRepository.delete(updatedBooking.id);
      return { status: 'deleted' }; 
    }
    
    return updatedBooking;
  }

  async getLockedSeats(showtimeId) {
    return await this.bookingRepository.findLockedSeats(showtimeId);
  }

  async getAllBookings() {
    return await this.bookingRepository.findAll();
  }

  async getBookingById(id) {
    return await this.bookingRepository.findById(id);
  }

  async getBookingsByUserId(userId) {
    return await this.bookingRepository.findByUserId(userId);
  }

  async confirmBooking(id) {
    const booking = await this.bookingRepository.findById(id);
    if (!booking) return null;
    
    // Create updated booking object or partial update
    // Since repository update expects an object with properties
    const updateData = {
        ...booking,
        status: 'confirmed',
        expiresAt: null // Clear expiration
    };

    if (this.validationService && !updateData.validationToken) {
        updateData.validationToken = this.validationService.generateValidationToken(id);
    }
    
    return await this.bookingRepository.update(id, updateData);
  }

  async validateBooking(token) {
    if (!this.validationService) {
      throw new Error('Validation service not initialized');
    }

    try {
      const decoded = this.validationService.verifyValidationToken(token);
      const bookingId = decoded.bookingId;

      const booking = await this.bookingRepository.findById(bookingId);
      if (!booking) {
        return { status: 'invalid', message: 'Booking not found' };
      }

      // Check if token matches stored token (security measure)
      if (booking.validationToken !== token) {
        return { status: 'invalid', message: 'Token mismatch' };
      }

      if (booking.status === 'redeemed') {
        return { 
          status: 'redeemed', 
          message: 'Ticket already redeemed',
          booking: {
            id: booking.id,
            seats: booking.seatIds
          }
        };
      }

      if (booking.status !== 'confirmed') {
        return { status: 'invalid', message: `Booking status is ${booking.status}` };
      }

      return {
        status: 'valid',
        booking: {
          id: booking.id,
          seats: booking.seatIds,
          totalPrice: booking.totalPrice
        }
      };
    } catch (error) {
      return { status: 'invalid', message: error.message };
    }
  }

  async cancelBooking(id) {
    const booking = await this.bookingRepository.findById(id);
    if (!booking) return null;

    if (booking.couponCode && this.couponService) {
      await this.couponService.decrementUsage(booking.couponCode);
    }

    const updateData = {
        ...booking,
        status: 'cancelled'
    };

    return await this.bookingRepository.update(id, updateData);
  }
}

module.exports = BookingService;