// Booking service
const Booking = require('../domain/Booking');

class BookingService {
  constructor(bookingRepository) {
    this.bookingRepository = bookingRepository;
  }

  async createBooking(bookingData) {
    const booking = new Booking(
      null, // ID will be generated by database
      bookingData.userId,
      bookingData.showtimeId,
      bookingData.seatIds,
      bookingData.totalPrice,
      new Date(),
      bookingData.paymentMethod === 'cash' ? 'confirmed' : 'pending', // For cash payments, immediately confirm
      bookingData.paymentMethod // payment method
    );

    return await this.bookingRepository.create(booking);
  }

  async getAllBookings() {
    return await this.bookingRepository.findAll();
  }

  async getBookingById(id) {
    return await this.bookingRepository.findById(id);
  }

  async getBookingsByUserId(userId) {
    return await this.bookingRepository.findByUserId(userId);
  }

  async confirmBooking(id) {
    const booking = await this.bookingRepository.findById(id);
    if (booking) {
      booking.status = 'confirmed';
      return await this.bookingRepository.update(id, booking);
    }
    return null;
  }

  async cancelBooking(id) {
    const booking = await this.bookingRepository.findById(id);
    if (booking) {
      booking.status = 'cancelled';
      return await this.bookingRepository.update(id, booking);
    }
    return null;
  }
}

module.exports = BookingService;