// Booking service
const Booking = require('../domain/Booking');

class BookingService {
  constructor(bookingRepository) {
    this.bookingRepository = bookingRepository;
  }

  async createBooking(bookingData) {
    // Check for existing held booking to upgrade
    const existingHold = await this.bookingRepository.findPendingBookingByUser(bookingData.userId, bookingData.showtimeId);

    if (existingHold) {
      // Verify all requested seats are available (or held by this user)
      for (const seatId of bookingData.seatIds) {
        const collision = await this.bookingRepository.findCollidingBooking(bookingData.showtimeId, seatId, bookingData.userId);
        if (collision) {
          throw new Error(`Seat ${seatId} is no longer available`);
        }
      }

      const updatedBooking = new Booking(
        existingHold.id,
        bookingData.userId,
        bookingData.showtimeId,
        bookingData.seatIds,
        bookingData.totalPrice,
        new Date(),
        bookingData.paymentMethod === 'cash' ? 'confirmed' : 'pending',
        bookingData.paymentMethod
      );
      
      // Clear expiration if confirmed, or keep/update if pending payment?
      // If pending payment, we probably still want an expiration (e.g. 15 mins to pay)
      // But existing logic might not use expiresAt for 'pending' status in the same way.
      // Let's set it to null if confirmed, or +15 mins if pending.
      if (updatedBooking.status === 'confirmed') {
        updatedBooking.expiresAt = null;
      } else {
        updatedBooking.expiresAt = new Date(Date.now() + 15 * 60 * 1000); 
      }

      // We need to pass the object structure expected by repository.update
      // The repository expects a generic object or booking instance.
      // Looking at MongoBookingRepository.update, it extracts fields.
      // So passing the Booking instance is fine.
      return await this.bookingRepository.update(existingHold.id, updatedBooking);
    }

    // New booking (fallback)
    // Check collisions first
    for (const seatId of bookingData.seatIds) {
        const collision = await this.bookingRepository.findCollidingBooking(bookingData.showtimeId, seatId, bookingData.userId);
        if (collision) {
          throw new Error(`Seat ${seatId} is no longer available`);
        }
    }

    const booking = new Booking(
      null, // ID will be generated by database
      bookingData.userId,
      bookingData.showtimeId,
      bookingData.seatIds,
      bookingData.totalPrice,
      new Date(),
      bookingData.paymentMethod === 'cash' ? 'confirmed' : 'pending', // For cash payments, immediately confirm
      bookingData.paymentMethod // payment method
    );
    
    if (booking.status === 'pending') {
       booking.expiresAt = new Date(Date.now() + 15 * 60 * 1000);
    }

    return await this.bookingRepository.create(booking);
  }

  async holdSeat(userId, showtimeId, seatId) {
    // 1. Check if seat is already locked by someone else
    const collision = await this.bookingRepository.findCollidingBooking(showtimeId, seatId, userId);
    if (collision) {
      throw new Error('Seat is already reserved');
    }

    // 2. Find existing active hold for this user
    let booking = await this.bookingRepository.findPendingBookingByUser(userId, showtimeId);

    const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes from now

    if (booking) {
      // Check max seats (e.g. 8)
      if (booking.seatIds.length >= 8) {
        throw new Error('Maximum seat limit reached (8)');
      }
      return await this.bookingRepository.addSeatToBooking(booking.id, seatId, expiresAt);
    } else {
      const newBooking = new Booking(
        null,
        userId,
        showtimeId,
        [seatId],
        0, 
        new Date(),
        'held',
        'momo',
        expiresAt
      );
      return await this.bookingRepository.create(newBooking);
    }
  }

  async releaseSeat(userId, showtimeId, seatId) {
    const booking = await this.bookingRepository.findPendingBookingByUser(userId, showtimeId);
    if (!booking) return null;

    const updatedBooking = await this.bookingRepository.removeSeatFromBooking(booking.id, seatId);
    
    if (updatedBooking && updatedBooking.seatIds.length === 0) {
      await this.bookingRepository.delete(updatedBooking.id);
      return { status: 'deleted' }; 
    }
    
    return updatedBooking;
  }

  async getLockedSeats(showtimeId) {
    return await this.bookingRepository.findLockedSeats(showtimeId);
  }

  async getAllBookings() {
    return await this.bookingRepository.findAll();
  }

  async getBookingById(id) {
    return await this.bookingRepository.findById(id);
  }

  async getBookingsByUserId(userId) {
    return await this.bookingRepository.findByUserId(userId);
  }

  async confirmBooking(id) {
    const booking = await this.bookingRepository.findById(id);
    if (!booking) return null;
    
    // Create updated booking object or partial update
    // Since repository update expects an object with properties
    const updateData = {
        ...booking,
        status: 'confirmed',
        expiresAt: null // Clear expiration
    };
    
    return await this.bookingRepository.update(id, updateData);
  }

  async cancelBooking(id) {
    const booking = await this.bookingRepository.findById(id);
    if (!booking) return null;

    const updateData = {
        ...booking,
        status: 'cancelled'
    };

    return await this.bookingRepository.update(id, updateData);
  }
}

module.exports = BookingService;