// Movie service
const Movie = require('../domain/Movie');

class MovieService {
  constructor(movieRepository) {
    this.movieRepository = movieRepository;
  }

  async createMovie(movieData) {
    const movie = new Movie(
      null, // ID will be generated by database
      movieData.title,
      movieData.director,
      movieData.cast,
      movieData.synopsis,
      movieData.duration,
      movieData.genre,
      movieData.rating,
      movieData.posterUrl || '', // Use the uploaded file path or empty string
      movieData.trailerUrl,
      movieData.releaseDate,
      movieData.endDate,
      movieData.formats || ['2D']
    );

    return await this.movieRepository.create(movie);
  }

  async getMovieById(id) {
    return await this.movieRepository.findById(id);
  }

  async getAllMovies(page, limit, search, format) {
    return await this.movieRepository.findAll(page, limit, search, format);
  }

  async getNowShowing(page, limit, format) {
    return await this.movieRepository.findNowShowing(page, limit, format);
  }

  async getComingSoon(page, limit, format) {
    return await this.movieRepository.findComingSoon(page, limit, format);
  }

  async updateMovie(id, movieData) {
    const movie = new Movie(
      id,
      movieData.title,
      movieData.director,
      movieData.cast,
      movieData.synopsis,
      movieData.duration,
      movieData.genre,
      movieData.rating,
      movieData.posterUrl || '', // Use the uploaded file path or empty string
      movieData.trailerUrl,
      movieData.releaseDate,
      movieData.endDate,
      movieData.formats
    );

    return await this.movieRepository.update(id, movie);
  }

  async deleteMovie(id) {
    return await this.movieRepository.delete(id);
  }
}

module.exports = MovieService;