// Showtime service
const Showtime = require('../domain/Showtime');

class ShowtimeService {
  constructor(showtimeRepository) {
    this.showtimeRepository = showtimeRepository;
  }

  async createShowtime(showtimeData) {
    const showtime = new Showtime(
      null, // ID will be generated by database
      showtimeData.movieId,
      showtimeData.theaterId,
      showtimeData.showDate,
      showtimeData.showTime,
      showtimeData.format,
      showtimeData.language,
      showtimeData.price
    );

    return await this.showtimeRepository.create(showtime);
  }

  async getAllShowtimes(page = 1, limit = 10) {
    return await this.showtimeRepository.findAll(page, limit);
  }

  async getShowtimeById(id) {
    return await this.showtimeRepository.findById(id);
  }

  async getShowtimesByMovieId(movieId) {
    return await this.showtimeRepository.findByMovieId(movieId);
  }

  async getFutureShowtimesByMovieId(movieId) {
    const showtimes = await this.showtimeRepository.findFutureByMovieId(movieId);
    const now = new Date();
    // Filter out 'Past' showtimes and add status
    return showtimes
      .filter(st => this.getShowtimeStatus(st, now) !== 'Past')
      .map(st => ({ ...st, status: this.getShowtimeStatus(st, now) }));
  }

  async getShowtimesByDateAndTheater(date, theaterId, filterPast = false) {
    const showtimes = await this.showtimeRepository.findByDateAndTheater(date, theaterId);
    const now = new Date();
    let result = showtimes;
    if (filterPast) {
      result = showtimes.filter(st => this.getShowtimeStatus(st, now) !== 'Past');
    }
    return result.map(st => ({ ...st, status: this.getShowtimeStatus(st, now) }));
  }

  async getShowtimesByDate(date, filterPast = false) {
    const showtimes = await this.showtimeRepository.findByDate(date);
    const now = new Date();
    let result = showtimes;
    if (filterPast) {
      result = showtimes.filter(st => this.getShowtimeStatus(st, now) !== 'Past');
    }
    return result.map(st => ({ ...st, status: this.getShowtimeStatus(st, now) }));
  }

  async updateShowtime(id, showtimeData) {
    const showtime = new Showtime(
      id,
      showtimeData.movieId,
      showtimeData.theaterId,
      showtimeData.showDate,
      showtimeData.showTime,
      showtimeData.format,
      showtimeData.language,
      showtimeData.price
    );

    return await this.showtimeRepository.update(id, showtime);
  }

  async deleteShowtime(id) {
    return await this.showtimeRepository.delete(id);
  }

  getShowtimeStatus(showtime, currentTime = new Date()) {
    const startDateTime = new Date(showtime.showDate);
    // showTime format is "HH:mm"
    const [hours, minutes] = showtime.showTime.split(':').map(Number);
    startDateTime.setUTCHours(hours, minutes, 0, 0);

    const diffInMs = startDateTime.getTime() - currentTime.getTime();
    const diffInMinutes = diffInMs / (1000 * 60);

    if (diffInMinutes <= 0) {
      return 'Past';
    } else if (diffInMinutes <= 15) {
      return 'Closed';
    } else {
      return 'Active';
    }
  }
}

module.exports = ShowtimeService;