// Showtime service
const Showtime = require('../domain/Showtime');

class ShowtimeService {
  constructor(showtimeRepository) {
    this.showtimeRepository = showtimeRepository;
  }

  async createShowtime(showtimeData) {
    const showtime = new Showtime(
      null, // ID will be generated by database
      showtimeData.movieId,
      showtimeData.theaterId,
      showtimeData.showDate,
      showtimeData.showTime,
      showtimeData.format,
      showtimeData.language,
      showtimeData.price
    );
    
    return await this.showtimeRepository.create(showtime);
  }

  async getShowtimeById(id) {
    return await this.showtimeRepository.findById(id);
  }

  async getShowtimesByMovieId(movieId) {
    return await this.showtimeRepository.findByMovieId(movieId);
  }

  async getShowtimesByDateAndTheater(date, theaterId) {
    return await this.showtimeRepository.findByDateAndTheater(date, theaterId);
  }

  async updateShowtime(id, showtimeData) {
    const showtime = new Showtime(
      id,
      showtimeData.movieId,
      showtimeData.theaterId,
      showtimeData.showDate,
      showtimeData.showTime,
      showtimeData.format,
      showtimeData.language,
      showtimeData.price
    );
    
    return await this.showtimeRepository.update(id, showtime);
  }

  async deleteShowtime(id) {
    return await this.showtimeRepository.delete(id);
  }
}

module.exports = ShowtimeService;