// User service
const User = require('../domain/User');
const bcrypt = require('bcryptjs');

class UserService {
  constructor(userRepository) {
    this.userRepository = userRepository;
  }

  async createUser(userData) {
    // Hash the password before storing
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash(userData.password, saltRounds);
    
    // Only allow setting role to 'admin' if specified in userData
    // In production, this should be more secure (e.g., only allow admins to create admins)
    const role = userData.role && userData.role === 'admin' ? 'admin' : 'user';
    
    const user = new User(
      null, // ID will be generated by database
      userData.name,
      userData.email,
      userData.phone,
      hashedPassword,
      userData.dateOfBirth,
      0, // initial loyalty points
      role
    );
    
    return await this.userRepository.create(user);
  }

  async getUserById(id) {
    return await this.userRepository.findById(id);
  }

  async getUserByEmail(email) {
    return await this.userRepository.findByEmail(email);
  }

  async updateUser(id, userData) {
    const user = new User(
      id,
      userData.name,
      userData.email,
      userData.phone,
      userData.passwordHash,
      userData.dateOfBirth,
      userData.loyaltyPoints,
      userData.role || 'user'
    );
    
    return await this.userRepository.update(id, user);
  }

  async deleteUser(id) {
    return await this.userRepository.delete(id);
  }

  async authenticateUser(email, password) {
    const user = await this.userRepository.findByEmail(email);
    if (user && await bcrypt.compare(password, user.passwordHash)) {
      return user;
    }
    return null;
  }
}

module.exports = UserService;